package Main;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;


/*
 * Contact Manager
 *
 * Created by WilliamBD
 * On March 30 2018
 * To manage Contacts
 */

/**
 *
 * @author widea
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Search = new javax.swing.JPanel();
        SearchTitle = new javax.swing.JLabel();
        SearchFNLabel = new javax.swing.JLabel();
        SearchHPLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        SearchFN = new javax.swing.JTextField();
        SearchContact = new javax.swing.JButton();
        SearchHP = new javax.swing.JTextField();
        SearchCPLabel = new javax.swing.JLabel();
        SearchCP = new javax.swing.JTextField();
        SearchELabel = new javax.swing.JLabel();
        SearchE = new javax.swing.JTextField();
        SearchALabel = new javax.swing.JLabel();
        SearchA = new javax.swing.JTextField();
        ChangeInfo = new javax.swing.JButton();
        ChangeConf = new javax.swing.JLabel();
        Add = new javax.swing.JPanel();
        AddTitle = new javax.swing.JLabel();
        AddFNLabel = new javax.swing.JLabel();
        AddHPLabel = new javax.swing.JLabel();
        AddCPLabel = new javax.swing.JLabel();
        AddELabel = new javax.swing.JLabel();
        AddContact = new javax.swing.JButton();
        AddFN = new javax.swing.JTextField();
        AddHP = new javax.swing.JTextField();
        AddCP = new javax.swing.JTextField();
        AddE = new javax.swing.JTextField();
        AddALabel = new javax.swing.JLabel();
        AddA = new javax.swing.JTextField();
        AddConfirm = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        Subtitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(179, 223, 76));

        SearchTitle.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        SearchTitle.setText("Search Contacts");

        SearchFNLabel.setText("Full Name:");

        SearchHPLabel.setText("Home Phone:");

        SearchContact.setText("Search");
        SearchContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchContactActionPerformed(evt);
            }
        });

        SearchCPLabel.setText("Cell Phone:");

        SearchELabel.setText("Email:");

        SearchALabel.setText("Address:");

        ChangeInfo.setText("Change Info");
        ChangeInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeInfoActionPerformed(evt);
            }
        });

        ChangeConf.setFont(new java.awt.Font("Ubuntu", 2, 18)); // NOI18N
        ChangeConf.setForeground(new java.awt.Color(1, 119, 84));

        javax.swing.GroupLayout SearchLayout = new javax.swing.GroupLayout(Search);
        Search.setLayout(SearchLayout);
        SearchLayout.setHorizontalGroup(
            SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(SearchLayout.createSequentialGroup()
                .addGroup(SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SearchLayout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(SearchTitle))
                    .addGroup(SearchLayout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(SearchFNLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SearchFN, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SearchLayout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(SearchContact))
                    .addGroup(SearchLayout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addGroup(SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SearchHPLabel)
                            .addComponent(SearchCPLabel)
                            .addComponent(SearchELabel)
                            .addComponent(SearchALabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SearchHP)
                            .addComponent(SearchCP)
                            .addComponent(SearchE)
                            .addComponent(SearchA, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))))
                .addContainerGap(111, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SearchLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ChangeInfo)
                .addGap(31, 31, 31)
                .addComponent(ChangeConf, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        SearchLayout.setVerticalGroup(
            SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SearchTitle)
                .addGap(26, 26, 26)
                .addGroup(SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchFNLabel)
                    .addComponent(SearchFN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SearchContact)
                .addGap(10, 10, 10)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchHPLabel)
                    .addComponent(SearchHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchCPLabel)
                    .addComponent(SearchCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchELabel)
                    .addComponent(SearchE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchALabel)
                    .addComponent(SearchA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ChangeInfo)
                    .addComponent(ChangeConf, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        jTabbedPane1.addTab("SearchContacts", Search);

        AddTitle.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        AddTitle.setText("Add Contact");

        AddFNLabel.setText("Full Name:");

        AddHPLabel.setText("Home Phone:");

        AddCPLabel.setText("Cell Phone:");

        AddELabel.setText("Email:");

        AddContact.setText("Add Contact");
        AddContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddContactActionPerformed(evt);
            }
        });

        AddFN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFNActionPerformed(evt);
            }
        });

        AddALabel.setText("Address:");

        AddConfirm.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        AddConfirm.setForeground(new java.awt.Color(19, 127, 93));

        javax.swing.GroupLayout AddLayout = new javax.swing.GroupLayout(Add);
        Add.setLayout(AddLayout);
        AddLayout.setHorizontalGroup(
            AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddLayout.createSequentialGroup()
                .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddLayout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(AddTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AddLayout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AddLayout.createSequentialGroup()
                                .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(AddFNLabel)
                                    .addComponent(AddHPLabel)
                                    .addComponent(AddCPLabel)
                                    .addComponent(AddELabel)
                                    .addComponent(AddALabel))
                                .addGap(18, 18, 18)
                                .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(AddE, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                                    .addComponent(AddCP)
                                    .addComponent(AddHP)
                                    .addComponent(AddFN)
                                    .addComponent(AddA)))
                            .addGroup(AddLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(AddContact))
                            .addGroup(AddLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(AddConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        AddLayout.setVerticalGroup(
            AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddTitle)
                .addGap(29, 29, 29)
                .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddFNLabel)
                    .addComponent(AddFN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddHPLabel)
                    .addComponent(AddHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddCPLabel)
                    .addComponent(AddCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddELabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddALabel)
                    .addComponent(AddA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(AddConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddContact)
                .addContainerGap())
        );

        jTabbedPane1.addTab("AddContact", Add);

        Title.setFont(new java.awt.Font("Century Schoolbook L", 1, 24)); // NOI18N
        Title.setText("Contact Manager");

        Subtitle.setText("Created By WilliamBD");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(Subtitle)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Subtitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//used to know which line a worked with contact is on, useful for changing data.
int contactLine;

    private void AddContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddContactActionPerformed
        try {
            //finds file and sets up file reader
            String fileName = "Contacts.txt";
            File jarFile = new File(MainPage.class.getProtectionDomain().getCodeSource().getLocation().toURI().getPath());
            String inputFilePath = jarFile.getParent() + File.separator + fileName;
            File f = new File(inputFilePath);
            FileReader fr = new FileReader(f);
            BufferedReader br = new BufferedReader(fr);
            
            //Collect contact info
            String Name = AddFN.getText();
            String HPhone = AddHP.getText();
            String CPhone = AddCP.getText();
            String Email = AddE.getText();
            String Address = AddA.getText();
            
            //temporarily stores contact info
            List<String> contacts = new ArrayList<String>();
            String line;
            
            //reads all lines in file, then stores them.
            do{
                line = br.readLine();
                if (line==null){
                    break;
                }
                contacts.add(line);
            }while (line != null);
            
            //close writers.
            br.close();
            fr.close();
            
            //prepares for writing.
            FileWriter fw = new FileWriter(f);
            
            //adds new contacts to data in memory.
            contacts.add(Name+"#"+HPhone+"#"+CPhone+"#"+Email+"#"+Address);
            
            //copies data in memory to text file.
            for (String str : contacts){
                fw.write(str);
                fw.write("\n");
            }
            
            //closes writer
            fw.close();
            
            AddConfirm.setText(Name+" has been added to contacts");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (URISyntaxException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AddContactActionPerformed

    private void AddFNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddFNActionPerformed

    private void SearchContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchContactActionPerformed

        try {
            //prepares files and reader
            String fileName = "Contacts.txt";
            File jarFile = new File(MainPage.class.getProtectionDomain().getCodeSource().getLocation().toURI().getPath());
            String inputFilePath = jarFile.getParent() + File.separator + fileName;
            File f = new File(inputFilePath);
            FileReader fr = new FileReader(f);
            BufferedReader br = new BufferedReader(fr);
            
            //gets input of name
            String name = SearchFN.getText();
            
            //variables for looping
            String line;
            String[] items;
            int liNum = 0;
            
            //loops through each line until the proper name is found then outputs.
            do{
                line = br.readLine();
                
                //ends if null line
                if (line == null){
                    break;
                }
                
                //splits line into individual data (storage is split by #'s
                items = line.split("#");
                
                //checks for the name
                if (items[0].equals(name)){
                    
                    //outputs all the text
                    SearchHP.setText(items[1]);
                    SearchCP.setText(items[2]);
                    SearchE.setText(items[3]);
                    SearchA.setText(items[4]);
                    
                    //sets line where data is located, if needed for a data change.
                    contactLine = liNum;
                    break;
                }
                //adds 1 to linum so that we know which line we are reading.
                liNum++;
                
            }while(line!= null);
            
            br.close();
            fr.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (URISyntaxException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SearchContactActionPerformed

    private void ChangeInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeInfoActionPerformed
        FileReader fr = null;
        try {
            //prepare file
            String fileName = "Contacts.txt";
            File jarFile = new File(MainPage.class.getProtectionDomain().getCodeSource().getLocation().toURI().getPath());
            String inputFilePath = jarFile.getParent() + File.separator + fileName;
            File f = new File(inputFilePath);
            
            //prepare reading
            fr = new FileReader(f);
            BufferedReader br = new BufferedReader(fr);
            
            //take data from file
            String Name = SearchFN.getText();
            String HPhone = SearchHP.getText();
            String CPhone = SearchCP.getText();
            String Email = SearchE.getText();
            String Address = SearchA.getText();
            
            //temporarily stores contact info
            List<String> contacts = new ArrayList<String>();
            
            //variables for looping
            String line;
            int i = 0;
            
            //reads all lines in file, then stores them.
            do{
                //reads line
                line = br.readLine();
                
                //checks if line is null
                if (line==null){
                    break;
                }
                
                //if this is the line we want to edit, we edit it.
                if (i == contactLine){
                    contacts.add(Name+"#"+HPhone+"#"+CPhone+"#"+Email+"#"+Address);
                }else{
                contacts.add(line);
                }
                i++;
            }while (line != null);
            
            //close writers.
            br.close();
            fr.close();
            
            //prepares writer
            FileWriter fw = new FileWriter(f);
            
            //copies data in memory to text file.
            for (String str : contacts){
                fw.write(str);
                fw.write("\n");
            }
            
            //closes writer
            fw.close();
            ChangeConf.setText("Change Confirmed");
            
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (URISyntaxException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ChangeInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Add;
    private javax.swing.JTextField AddA;
    private javax.swing.JLabel AddALabel;
    private javax.swing.JTextField AddCP;
    private javax.swing.JLabel AddCPLabel;
    private javax.swing.JLabel AddConfirm;
    private javax.swing.JButton AddContact;
    private javax.swing.JTextField AddE;
    private javax.swing.JLabel AddELabel;
    private javax.swing.JTextField AddFN;
    private javax.swing.JLabel AddFNLabel;
    private javax.swing.JTextField AddHP;
    private javax.swing.JLabel AddHPLabel;
    private javax.swing.JLabel AddTitle;
    private javax.swing.JLabel ChangeConf;
    private javax.swing.JButton ChangeInfo;
    private javax.swing.JPanel Search;
    private javax.swing.JTextField SearchA;
    private javax.swing.JLabel SearchALabel;
    private javax.swing.JTextField SearchCP;
    private javax.swing.JLabel SearchCPLabel;
    private javax.swing.JButton SearchContact;
    private javax.swing.JTextField SearchE;
    private javax.swing.JLabel SearchELabel;
    private javax.swing.JTextField SearchFN;
    private javax.swing.JLabel SearchFNLabel;
    private javax.swing.JTextField SearchHP;
    private javax.swing.JLabel SearchHPLabel;
    private javax.swing.JLabel SearchTitle;
    private javax.swing.JLabel Subtitle;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
